version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=conrad
      - INFLUXDB_ADMIN_USER=conrad
      - INFLUXDB_ADMIN_PASSWORD=711724Cope
      - INFLUXDB_USER=conrad
      - INFLUXDB_USER_PASSWORD=711724Cope
    networks:
      - mynetwork

  stock_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - ticker=${ticker}
    depends_on:
      - influxdb
    networks:
      - mynetwork

networks:
  mynetwork: