version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - my_network

  python-app:
    build: analise_fundamentalista.py
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - ticker=ITUB4.SA
    command: python3 analise_fundamentalista.py
    depends_on:
      - influxdb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
