# Use a imagem oficial do InfluxDB como base
FROM influxdb:latest

# Configuração do token de InfluxDB
ENV INFLUXTOKEN=3B-M63BZ8X-j9_WX5A1lHfpdfNlD-Myx5wvFBKAQyFM3qW3OOQtK2vTOVplXXum2CKnZd1GqvX9BUvczxsVmlQ==

# Porta padrão do InfluxDB
EXPOSE 8086

# Comando de inicialização
CMD ["influxd"]
